Repository fusionjs/fusion-plugin-universal-events-react, pull requests merged in 2018-11, with the labels that each got.

#145 Fix flow
  package.json
  src/plugin.js
  yarn.lock
Labels: bugfix, dependencies

#148 Release v1.0.3
  package.json
Labels: release

#149 Upgrade dependencies
  package.json
  yarn.lock
Labels: greenkeeping
