Repository fusionjs/fusion-plugin-universal-events-react, pull requests merged in 2019-01, with the labels that each got.

#156 Upgrade dependencies
  package.json
  yarn.lock
Labels: bugfix, greenkeeping

#158 Use fusion-plugin-universal-events@^1.3.1-0
  package.json
  yarn.lock
Labels: bugfix, dependencies, greenkeeping

#159 Release v1.0.5-0
  package.json
Labels: release

#163 Release v1.0.5-1
  package.json
Labels: release

#164 Release v1.0.5
  package.json
Labels: release

#165 Upgrade fusion-plugin-universal-events
  package.json
  yarn.lock
Labels: greenkeeping

#166 Release v1.0.6
  package.json
Labels: release

#167 Upgrade fusion-plugin-universal-events
  package.json
  yarn.lock
Labels: bugfix

#168 Release v1.0.7
  package.json
Labels: release

#169 Upgrade flow-bin@latest and any packages raising Flow complaints
  package.json
  yarn.lock
Labels: bugfix
