Repository fusionjs/fusion-plugin-universal-events-react, pull requests merged in 2019-03, with the labels that each got.

#180 Bump fusion-plugin-universal-events dependency to latest pre-release
  package.json
  yarn.lock
Labels: bugfix

#179 Release v1.0.9-0
  package.json
Labels: release

#182 Update fusion-plugin-universal-events to @latest
  package.json
  yarn.lock
Labels: bugfix, greenkeeping

#181 Release v1.0.9
  package.json
Labels: release

#183 Update fusion-react peer dep
  package.json
Labels: greenkeeping
